version: '3.5'
services:
  daemon:
    image: nickadam/backup-to-smb:1.0
    build: .
    environment:
      CRON_SCHEDULE: '* * * * *'
      BACKUP_NAME: some application
      RETENTION: 1
      SMB_SHARE: //server/share/folder
      SMB_USER: smbusername
      #SMB_PASS: smbpassword
      SMB_PASS_FILE: /run/secrets/smbpassword
    secrets:
      - smbpassword
    volumes:
      - type: volume
        source: data
        target: /data
volumes:
  data:
secrets:
  smbpassword:
    external: true
